### ISSUE TITLE
Relative time cannot be specified in seconds

### ISSUE THREAD

**Issue by richardgaunt** [drevops/behat-steps#228]
We cannot run tests that are `[relative:+5seconds]` because of the way relative dates are created in the `DateTrait`

https://github.com/drevops/behat-steps/blob/main/src/DateTrait.php#L90

Currently:
` $now = $now ?: strtotime(date('Y-m-d H:i:00', time()));`

Should be:

` $now = $now ?: strtotime(date('Y-m-d H:i:s', time()));`

There might be a reason  behind this that I am not aware - but happy to create a PR if its ok to change.

**Comment by AlexSkrypnyk** [comment]
@richardgaunt 
Thank you for reporting this. There is no reason to use `00` for seconds. I think this is a defect.

We have a test for this, but it does not test the seconds. If you are planning to provide a PR, could you please provide a test with seconds. 

thanks

**Comment by AlexSkrypnyk** [comment]
@tannguyen04 
Can you please pick this one up.

Please update the step definition code to support seconds and also add additional test cases for:
+ 5 seconds
+ 30 seconds
+ 65 seconds
