### ISSUE TITLE
Document move to drevops namespace

### ISSUE THREAD

**Issue by xurizaemon** [drevops/behat-steps#87]
Following on from #76

Should we introduce some docs on any steps projects should to take for the update?

Context: I noticed this get picked up on a `composer update --lock` today and wondered if it might confuse people that the *new* package name is abandoned (see bottom of diff screenshot).

![image](https://user-images.githubusercontent.com/105608/126719923-5d554b3c-540e-4adf-b0da-fb8e506a6dad.png)

My expectation is that requiring the old name will continue to work, but if there's room for confusion or better guidance then happy to assist adding that. Maybe just a few words in the README's installation section to address it?

**Comment by xurizaemon** [comment]
What I hadn't spotted was the output from `composer update`:

> Package integratedexperts/behat-steps is abandoned, you should avoid using it. Use drevops/behat-steps instead.

That might be sufficient - but I think a note about the rename (and that it's the same package) might be useful in the README.

**Comment by AlexSkrypnyk** [comment]
@xurizaemon 
Thank you for your feedback
I was asking around in the community how to better implement this "change notification" and the response I got was that an abandonment message is sufficient enough.

The new name cannot work as Packagist does not allow to rename project namespace (it only allows to point to a GitHub package with new org namespace), so the whole project had to be re-created in Packagist.

What I will do now is add more information to release notes for `1.0.0`.

Readme also have updated information on how to include traits (using new namespace `DrevOps`):

```
<?php

use Drupal\DrupalExtension\Context\DrupalContext;
use DrevOps\BehatSteps\D7\ContentTrait;

/**
 * Defines application features from the specific context.
 */
class FeatureContext extends DrupalContext {

  use ContentTrait;

}
```

**Comment by AlexSkrypnyk** [comment]
Documented in https://github.com/drevops/behat-steps/releases/tag/1.0.0

please feel free to re-open
